# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: token_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13token_service.proto\"_\n\x11StoreTokenRequest\x12\x12\n\ntoken_uuid\x18\x01 \x01(\t\x12\x11\n\tuser_uuid\x18\x02 \x01(\t\x12\x0f\n\x07payload\x18\x03 \x01(\t\x12\x12\n\nip_address\x18\x04 \x01(\t\"%\n\x12StoreTokenResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32G\n\x0cTokenService\x12\x37\n\nStoreToken\x12\x12.StoreTokenRequest\x1a\x13.StoreTokenResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'token_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_STORETOKENREQUEST']._serialized_start=23
  _globals['_STORETOKENREQUEST']._serialized_end=118
  _globals['_STORETOKENRESPONSE']._serialized_start=120
  _globals['_STORETOKENRESPONSE']._serialized_end=157
  _globals['_TOKENSERVICE']._serialized_start=159
  _globals['_TOKENSERVICE']._serialized_end=230
# @@protoc_insertion_point(module_scope)
